
name: PR Checks
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache pnpm store
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.STORE_PATH }}
            **/node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

  lint:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Run linting
        run: pnpm run lint

  format:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Run formatting
        run: pnpm run format:check

  build:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-setup
        name: Base Setup
      - name: Debug Environment Variables
        run: env
      - name: Build app
        run: pnpm run build
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: apps/web/.next
          key: ${{ runner.os }}-build-store-${{ hashFiles('./apps/web/src') }}

  docker-publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/inkonchain/ink-kit:latest
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
