name: PR Checks
on: [pull_request]

jobs:
  install_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

  lint:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Run linting
        run: pnpm run lint

  format:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Run formatting checks
        run: pnpm run format:check

  build:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment Variables
        run: env
      - name: Build application
        run: pnpm run build
      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: |
            apps/web/.next
            apps/web/.next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('apps/web/src/**/*', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
