name: PR Checks
on: [pull_request]

jobs:
  install_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

  lint:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Run linting
        run: pnpm run lint

  format:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Run formatting
        run: pnpm run format:check

  build:
    needs: install_modules
    runs-on: ubuntu-latest
    steps:
      - name: Base Setup
        uses: ./.github/actions/base-setup
      - name: Debug Environment Variables
        run: env
      - name: Build app
        run: pnpm run build
      - name: Cache build
        uses: actions/cache@v4
        with:
          path: apps/web/.next
          key: ${{ runner.os }}-build-store-${{ hashFiles('apps/web/src/**/*') }}
